# # FROM node:19-alpine

# # # COPY package.json /app/
# # # COPY mongodb/ routes/ /app/
# # # COPY index.js /app/

# # # WORKDIR /app

# # # RUN npm install

FROM node:14

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
